### ISSUE TITLE
Link to docs

### ISSUE THREAD

**Issue by dhirschfeld** [vidartf/ipyscales#7]
It would be useful to have a link to the docs, either in the readme or the project description:

![image](https://user-images.githubusercontent.com/881019/45724548-14cd0a00-bbfa-11e8-9225-300a8418b2d9.png)

https://ipyscales.readthedocs.io/en/latest/index.html

**Comment by vidartf** [comment]
I just got the docs up and running yesterday :) Fixed in 41c240c1a2d284912b170ed9e8954cd423e90191.
